import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import { EventProvider } from "./context/EventContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Pendaftaran Event</title>
      </head>
      <body className="bg-gray-50 font-sans">
        <EventProvider>
          <header className="bg-indigo-600 text-white shadow-md">
            <div className="container mx-auto px-4 py-4 flex justify-between items-center">
              <h1 className="text-2xl font-bold">Event Registration</h1>
              <nav className="space-x-4">
                <Link
                  href="/"
                  className="font-medium hover:underline text-yellow-300">
                  Daftar Peserta
                </Link>
                <a
                  href="/daftar"
                  className="font-medium hover:underline text-white">
                  Daftar Baru
                </a>
              </nav>
            </div>
          </header>
          <main className="container mx-auto px-4 py-8">{children}</main>
        </EventProvider>
      </body>
    </html>
  );
}
